sonar.projectKey=security-analysis-c2936d1bf79afce6
sonar.sources=/usr/src
sonar.host.url=http://host.docker.internal:9000
sonar.exclusions=**/.git/**,**/.scannerwork/**,**/__pycache__/**,**/*.pyc,**/node_modules/**,**/trivy-report.json
sonar.scm.disabled=true
